package game;

public enum PlayerEnum {
	HASKEY, HASROCKETPLAN, HASROCKETBODY, HASROCKETENGINE, HASGAUNTLET, HASSOULSTONE, HASMINDSTONE, HASREALITYSTONE,
<<<<<<< HEAD
	HASPOWERSTONE, ROCKETDONE, HASTIMESTONE, HASPOWER,HASSUPERPOWER, HASGUN, HASEXOSKELETON, HASSPACESUIT,OXYGENPRODUCE, OXYGEN, EARTH,OXYGENTANKPRODUCE, OXYGENTANK
=======
	HASPOWERSTONE, ROCKETDONE, HASTIMESTONE, HASPOWER,HASSUPERPOWER, HASGUN, HASEXOSKELETON, HASSPACESUIT
>>>>>>> master

}
